apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mnist-pvc
  namespace: huggingface
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
